name = "WeaponSystems"
uuid = "9546f4ee-7fe2-43c4-b924-f2649be2f5c5"
authors = ["Irene Ndindabahizi", "Royal Millitary Academy, Belgium"]
version = "0.1.0"

[deps]
ExternalBallistics = "b491e135-ab2a-4d40-88dd-d272818f63e6"
ReferenceFrameRotations = "74f56ac7-18b3-5285-802d-d4bd4f104033"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
